### ISSUE TITLE
"Sent" screen should show recipients

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1015]
On `Sent` screen threads with only 1 message show current user's email address (as current user is message author)
But it's not useful information, it should show recipient's email instead, probably with prefix `To: ` (as done in Gmail app)

**Comment by tomholub** [comment]
possibly the same cause as https://github.com/FlowCrypt/flowcrypt-ios/issues/873

**Comment by sosnovsky** [comment]
Yes, the same logic as described in #873 can be applied to `Sent` screen too.

**Comment by ekievsky** [comment]
so, for example:

if evgenii - sent email to - anton ( and thread contains only 1 message )
we render: `To: anton`

if evgenii and anton have multiple messages in thread, we render
`evgenii, anton`

correct, @tomholub ?
and this should apply to `sent` and to `drafts` folders?

**Comment by tomholub** [comment]
Please do what Gmail does - usually the most sensible choice.

**Comment by ekievsky** [comment]
@tomholub 
in gmail iOS app in sent tab title is "me" - if there is just one sent email in thread
if there are multiple messages in thread, there is "me" + participants.

this is not same as description of this task, that's why I want to clarify what exactly I should present.

so. in this task we want to see in `sent` menu:
1) original version of task
`To: Anton` if I am sending email to Anton and there is only one message in thread
`Anton, Evgenii` if there are multiple emails in thread

2) gmail iOS app version
`me`  if I am sending email to Anton and there is only one message in thread
`Anton, me` if there are multiple emails in thread

**Comment by tomholub** [comment]
Please do option 2. But first please finalize #1031
