### ISSUE TITLE
prepare assets for testing decrypt errors

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1041]
@martgil please copy one message per error type from flowcrypt.compatibility account to e2e account:
 - wrong mdc
 - bad mdc
 - bad signature
 - key mismatch
 - wrong ascii armor checksum

you can export mime messages through gmail interface and copy them into the other account using Thunderbird. Before doing so, you may edit the subject to make sure it's meaningfully describing the error.

myself: I have to copy private key from compatibility account to e2e account so that some of these can be understood on the other account

sending credentials by email

**Comment by martgil** [comment]
Hi @tomholub, Good evening. I think I need the verification directly through the phone because my device was flagged as not recognized.

`This device isn’t recognized. For your security, Google wants to make sure it’s really you. `

Enter my phone number gives me this error after getting the creds from email

```
Couldn’t sign you in email@xyz.com
Google couldn’t verify this account belongs to you.
```

**Comment by tomholub** [comment]
Please try again - I've adjusted the settings on the account (I think)

**Comment by tomholub** [comment]
But first, try to log in on your laptop.

**Comment by martgil** [comment]
I'm using my laptop while logging in and, adding my phone number to pass the authentication but still no good. However, I send a message containing the eml and their respective error messages so that it can quickly help for testing.

<img width="435" alt="Screen Shot 2021-11-22 at 2 24 12 PM" src="https://user-images.githubusercontent.com/46025304/142810772-3eaaee7a-39b1-4679-a6a6-39e517c40776.png">

Thank you!

**Comment by martgil** [comment]
Hi @tomholub, 

Sorry if this takes a while. I have copied the eml files into the e2e account using Thunderbird. Could you please check if you are able to read them and if the private key from the compatibility is working from your end?

**Comment by tomholub** [comment]
That means you managed to log in?

**Comment by martgil** [comment]
Yes sir! I just tried it once more it worked.

**Comment by tomholub** [comment]
I'll close this, someone else can write tests for these.

**Comment by tomholub** [comment]
Thanks!
