### ISSUE TITLE
why UI test could be unstable on local machine

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#1056]
Just tried to run all tests on my local machine with following config changes:
```
deviceName: 'iPhone Simulator',
app: '/Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app',
```

I got two failed tests:
1.
```
[iPhone Simulator iOS 15.0 #0-8] Spec: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/inbox/ReadKeyMismatchEmail.spec.ts
[iPhone Simulator iOS 15.0 #0-8] Running: iPhone Simulator on iOS 15.0 executing /Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app
[iPhone Simulator iOS 15.0 #0-8] Session ID: 9ba8bc35-4ab7-4ff7-8fdb-4aecdaf7b20c
[iPhone Simulator iOS 15.0 #0-8]
[iPhone Simulator iOS 15.0 #0-8] INBOX: 
[iPhone Simulator iOS 15.0 #0-8]    ✖ user is able to view key mismatch email
[iPhone Simulator iOS 15.0 #0-8]
[iPhone Simulator iOS 15.0 #0-8] 1 failing (43.7s)
[iPhone Simulator iOS 15.0 #0-8]
[iPhone Simulator iOS 15.0 #0-8] 1) INBOX:  user is able to view key mismatch email
[iPhone Simulator iOS 15.0 #0-8] Error: element ("~e2e.enterprise.test@flowcrypt.com") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-8] Error: element ("~e2e.enterprise.test@flowcrypt.com") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-8]     at async EmailScreen.checkEmailAddress (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/email.screen.ts:61:5)
[iPhone Simulator iOS 15.0 #0-8]     at async EmailScreen.checkOpenedEmail (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/email.screen.ts:76:5)
[iPhone Simulator iOS 15.0 #0-8]     at async UserContext.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/inbox/ReadKeyMismatchEmail.spec.ts:22:5)
```
2.
```
[iPhone Simulator iOS 15.0 #0-11] Spec: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/settings/CheckSettingsForLoggedUser.spec.ts
[iPhone Simulator iOS 15.0 #0-11] Running: iPhone Simulator on iOS 15.0 executing /Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app
[iPhone Simulator iOS 15.0 #0-11] Session ID: ed3eb372-b62f-40d5-a044-21a72484abfd
[iPhone Simulator iOS 15.0 #0-11]
[iPhone Simulator iOS 15.0 #0-11] SETTINGS: 
[iPhone Simulator iOS 15.0 #0-11]    ✖ user should see public key and should not see private key
[iPhone Simulator iOS 15.0 #0-11]
[iPhone Simulator iOS 15.0 #0-11] 1 failing (38.2s)
[iPhone Simulator iOS 15.0 #0-11]
[iPhone Simulator iOS 15.0 #0-11] 1) SETTINGS:  user should see public key and should not see private key
[iPhone Simulator iOS 15.0 #0-11] Expected 'e2e' to contain '-----BEGIN PGP PUBLIC KEY BLOCK-----'.
[iPhone Simulator iOS 15.0 #0-11] Error: Expected 'e2e' to contain '-----BEGIN PGP PUBLIC KEY BLOCK-----'.
[iPhone Simulator iOS 15.0 #0-11]     at <Jasmine>
[iPhone Simulator iOS 15.0 #0-11]     at PublicKeyScreen.checkPublicKey (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/public-key.screen.ts:32:31)
[iPhone Simulator iOS 15.0 #0-11]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[iPhone Simulator iOS 15.0 #0-11]     at async UserContext.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/settings/CheckSettingsForLoggedUser.spec.ts:34:5)
```

On the other hand I see that on remote machine we have it green. Maybe we could discuss and find out how to have stable UI tests.

**Comment by tomholub** [comment]
Sometimes, what you are seeing is flakiness that is also present on the CI, but maybe less frequently.

Usually, these have to be investigated one by one. The most common way to improve flakiness is to ensure to wait until screen is fully loaded before grabbing content.

The other common issue is unstable/ambiguous query strings when looking for elements, like `the third element on the screen` and similar. We should always use accessibility identifiers.

This one definitely sounds like a combination of the two above:

```
[iPhone Simulator iOS 15.0 #0-11] Expected 'e2e' to contain '-----BEGIN PGP PUBLIC KEY BLOCK-----'.
```

As for this one:

```
[iPhone Simulator iOS 15.0 #0-8] Error: element ("~e2e.enterprise.test@flowcrypt.com") still not displayed after 15000ms
```

Sometimes we tap the previous button that goes us to that screen too early, before it can be interacted with. To fix this, we should add a delay into `waitAndClick` of a few hundred ms, which will ensure to wait a bit more after an element was displayed before interacting with it. (this was the problem with menu flakiness. The other problem was, the loading of menu is indeed too slow)

Finally, sometimes flakiness in ui tests is actually a problem with the app / codebase itself. This is another thing ui tests are valuable for - while 90% of flakiness is because of tests, the remaining 10% tend to be actual problems in the app that users may encounter.

Improvements I'm proposing:
 - test content always with `element.waitForContent("expected content")`. This will keep checking for presense of expected content repeatedly for up to 15 seconds and then throw. That way, you avoid "testing too early" which is the cause of 95% of flakiness of UI tests. This is what we do on browser extension.
 - never use position based element queries, instead always use accessibility identifiers. Add them to codebase when missing.

**Comment by sosnovsky** [comment]
Tests stability is much better after moving tests to mock apis, as previously it also was dependent on network requests. 
We also improved handling of elements presence and actions (with `waitAndClick`, `waitElementVisible` and other helpers)
