### ISSUE TITLE
Setup the app with Non-Gmail account(Other)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-ios#1200]
Hello, guys @Kharchevskyi @sosnovsky. Today I've tried to setup the app to connect to my local IMAS server. Unfortunately, I didn't complete it. The app showed me some errors. Currently, I'm working on https://github.com/FlowCrypt/flowcrypt-android/issues/1097 and would like to compare results between iOS and Android.

I have a question: does setup flow for `other` accounts work? If yes, how can we check what is wrong on my side?

More info:

1. I can connect to the local IMAP server from the Android app on the same machine
2. I can connect to the local IMAP server from the Android app from the same network (192.168.3.*)
3. I can connect to the local IMAP server from Linux via Thunderbird

**Comment by sosnovsky** [comment]
Hi @DenBond7, we had a big code refactoring (moved from custom Google `Promises` library to native iOS `async/await`) and IMAP functionality was broken since then. I think we haven't fixed it yet, as it's a low priority.
We are using e2e test gmail account for checking messages signatures - it has mails with all possible cases.

**Comment by DenBond7** [comment]
@sosnovsky thank you for the fast feedback. Got it. So we can leave it for later.

**Comment by tomholub** [comment]
tracked here https://github.com/FlowCrypt/flowcrypt-ios/issues/1181 so closing this one
