### ISSUE TITLE
UX - Log out button is missing on SetupInitialViewController

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#1241]
In case there is an error occurred during initial setup `SetupInitialViewController` only retry button present so it is not possible to log out.

![Simulator Screen Shot - iPhone 13 - 2021-12-22 at 10 59 47](https://user-images.githubusercontent.com/13693255/147065875-bcce4546-4f85-44fe-a472-7fc7582cb384.png)

**Comment by tomholub** [comment]
Also, the error doesn't print anything useful. We had a standardized way to make sure errors print out useful info, @sosnovsky could you please share what it was with examples? Then we could document it somewhere.

**Comment by tomholub** [comment]
Otherwise agree with this, there should be an "Use another account" button below, gray, that logs out.

**Comment by sosnovsky** [comment]
We have extension with `errorMessage` property for `Error` - https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Extensions/Error%2BExtension.swift#L12

It checks if `Error` has some custom message using `CustomStringConvertible` protocol, otherwise it uses `localizedDescription` property.

Here is example of error with custom messages - https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Functionality/Services/Compose%20Message%20Service/ComposeMessageError.swift

**Comment by Kharchevskyi** [comment]
`errorMessage` would not be helpful for this case, because it will print same localized description as it shown on a screenshot. 
For solving this particular case we need to adopt ImapError to CustomStringConvertible which actually should be done for all other errors to print useful information.
