### ISSUE TITLE
verify that migration test script in CI works

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1293]
1) create any schema change in db that doesn't break the app itself
2) don't create migration for it
3) push to a branch and make a draft PR
4) see if the CI breaks due to the unmigrated breaking change. It should, following https://github.com/FlowCrypt/flowcrypt-ios/issues/1148

If the CI breaks on the migration test but all other tests work, ok to close this issue (and the PR)

**Comment by Kharchevskyi** [comment]
Can I reopen this task? Need a bit more time for investigation. 
Looks like changes in PR #1312 treated by Realm as one that needs migration, which is strange.

**Comment by sosnovsky** [comment]
I think migration isn't required there as adding object property should be handled automatically, but we need to increment database scheme version, so app we'll know about scheme change.

**Comment by tomholub** [comment]
I'm reopening until a similar test PR is opened that would have caused a schema conflict

**Comment by tomholub** [comment]
@Kharchevskyi since you re-closed it without comment - please share what you found.

**Comment by Kharchevskyi** [comment]
1. I have pushed the commit to - `feature/issue-1293-migration-test` with changed schema
2. didn't create any migration (only schema version changed)
3. Test on ci failed - https://flowcrypt.semaphoreci.com/branches/020dc73b-4d68-43ca-91f2-0c1d2452d56f

**Comment by tomholub** [comment]
On https://flowcrypt.semaphoreci.com/jobs/21b93bee-b074-493b-a706-48c2266a041f there are many test failures unrelated to migration - doesn't count for verifying that the migration test works.

All tests except for the migration test should be passing to conclusively verify.

**Comment by Kharchevskyi** [comment]
@tomholub can you please clarify requirements?
1. create any schema change in db that doesn't break the app itself
- if we add some optional field to realm object without bumping schema version - app will crash
PR - #1312 (first commit)
CI run - https://flowcrypt.semaphoreci.com/jobs/ad47552d-203b-4b1d-b413-0b23a5fa7928
`✖ user should be able to check encrypted email, contacts after update app from old version`

- if we add some optional field and will bump db schema version - app will work as before
https://github.com/FlowCrypt/flowcrypt-ios/pull/1322 
CI run - https://flowcrypt.semaphoreci.com/jobs/976e4882-816d-477b-8a8a-e98cbf85f2fc
`✓ user should be able to check encrypted email, contacts after update app from old version`

- if we add a required field - we would need to perform db migration, otherwise app will crash

**Comment by tomholub** [comment]
We have a test that is supposed to break when we forget to do a migration.

Your task is to verify that the test works properly. @sosnovsky can answer further questions if needed.

**Comment by Kharchevskyi** [comment]
https://github.com/FlowCrypt/flowcrypt-ios/issues/1293#issuecomment-1017517798
Looks like works as expected. 

 `user should be able to check encrypted email, contacts after update app from old version` - failed in case there are no migration and passed if migration added.

**Comment by sosnovsky** [comment]
Looks good for me:

✅ test for migration from older app version fails on db scheme change
https://flowcrypt.semaphoreci.com/jobs/ad47552d-203b-4b1d-b413-0b23a5fa7928/summary?test-result-id=4ae71336-e44b-39bf-b9d2-752e234818a5

✅ all tests pass after database version bump
https://flowcrypt.semaphoreci.com/workflows/071f4fcb-01e1-4ef0-81c4-59923ec75c60/summary?test-result-id=4ae71336-e44b-39bf-b9d2-752e234818a5
