### ISSUE TITLE
Infinite call to fetchAndRenderEmailsOnly for empty folders

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#1366]
**SR:**
Open folder without any messages. Empty folder. 

```
"⚙️[InboxViewController] View did load"
"🔥[InboxViewController] fetchAndRenderEmailsOnly"
"🔥[InboxViewController] fetchAndRenderEmailsOnly"
"🔥[InboxViewController] fetchAndRenderEmailsOnly"
"🔥[InboxViewController] fetchAndRenderEmailsOnly"
"🔥[InboxViewController] fetchAndRenderEmailsOnly"
"🔥[InboxViewController] fetchAndRenderEmailsOnly"
"🔥[InboxViewController] fetchAndRenderEmailsOnly"
"🔥[InboxViewController] fetchAndRenderEmailsOnly"
```

Please double check that pagination for messages works. 
Open folder with a lot of messages and check that it loads new messages while scrolling to the bottom.

**Comment by tomholub** [comment]
Thanks for filing - how to reproduce?

**Comment by Kharchevskyi** [comment]
Updated description.

**Comment by sosnovsky** [comment]
@fcvakintos also noticed another issue with inbox pagination - when user opens `Inbox` screen it initially loads 2 pages of emails, instead of 1. It seems to be related to `willBeginBatchFetchWith` https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Controllers/Inbox/InboxViewController.swift#L216

Probably these 2 issues have the same origin, so I'll include this one here too
