### ISSUE TITLE
handle situation when refreshing keys from EKM and have no local keys

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1556]
I'll file another issue about this for the future. If no keys are present, then any pass phrase would be fine as long as it's strong enough. But then we need to also ask for the pass phrase second time to confirm it, like we do at initial setup, and we need to make sure the pass phrase is strong enough (same thing as setup).

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1510#discussion_r861973611_

**Comment by tomholub** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/6306961/165993436-61daabcb-eb63-400e-8d16-2ed19a74c50c.png">

**Comment by tomholub** [comment]
I guess the app should be more gracious in general when it finds itself in a situation with no keys. Which could happen - we will eventually implement removing keys from local storage when removed from EKM

**Comment by ioanmo226** [comment]
#1300 needs to be addressed first before this issue.
Because when no key pairs exists(when user logs into account but didn't finish EKM setup/Passphrase setup), currently app displays splash screen(which is wrong behavior).

![image](https://user-images.githubusercontent.com/77344191/174830895-4e226595-c0e8-4d7f-8a26-f91adecb20f0.png)
