### ISSUE TITLE
Add pass phrase expiration setting in settings screen

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1659]
Currently pass phrase expiration is hard-coded as 4 hours.
I think better to add this setting in settings page so that users change to whatever they want.

**Comment by ioanmo226** [comment]
@tomholub

**Comment by tomholub** [comment]
I agree it would be useful, but we didn't get that user request on any of the three platforms yet 🤷 

I think it's because for enterprises, the management chooses the desired time for users (for our main customer that was 4 hours) while non-enterprise users have an option to choose 4 hours or indefinite which seems to cover use cases for most people.

I will close it for now but will reopen if users or customers show interest in this.
