### ISSUE TITLE
Some emails are showing just plain html instead of text

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2099]
Currently app should strip html code and render just plain text for html emails. But it fails for some emails and showing just plain html, which makes it quite difficult to read message content.

**Comment by tomholub** [comment]
It's possible this problem only occurs when sending html email from browser extension in particular (only supported on Firefox, like this)

![image](https://user-images.githubusercontent.com/6306961/218106182-46861c8f-2206-4456-9f71-2772640dd7b4.png)

Because the format is not entirely correct. Maybe it works ok for HTML emails from other clients? (can check from flowcrypt.compatibility account later). If that is true, then the problem is only in recognizing it as a HTML message and treating it as such. We already had ability to parse and render HTML emails as text, to my knowledge.

**Comment by tomholub** [comment]
In either case, we already support rendering regular HTML emails as text, at the least, so we do have the functionality available to do this relatively easily.

**Comment by sosnovsky** [comment]
It happens not for FlowCrypt emails, but for some usual messages - for example, html isn't rendered for emails from reddit and for some email confirmation messages. I noticed that they start with such doctype:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0
Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/ xhtml1-strict.dtd">

<html xmIns="http://www.w3.org/1999/xhtm|"
...
```

While other html messages work well - showing plain text extracted from html.

**Comment by tomholub** [comment]
Ah. That must have been broken relatively recently.

**Comment by tomholub** [comment]
> Ah. That must have been broken relatively recently.

Or, it never worked for some types of html images. Please if you could, try adding a sample to flowcrypt.compatibility email and mention the subject here, to later have it ready as a sample.

**Comment by sosnovsky** [comment]
I think it was broken initially, as we didn't have any changes for html rendering recently. 
Will try to create sample email which fails to render and add it to flowcrypt.compatibility account

**Comment by sosnovsky** [comment]
@ioanmo226 I sent you example message which fails to render correctly on iOS

**Comment by ioanmo226** [comment]
Hmm.. IOS app renders exactly like browser extension.
Did I miss something?
![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/77344191/a1ebd197-c2b4-4573-a834-25c91b53d06d)

**Comment by sosnovsky** [comment]
Example message is in `ios-2099.eml`, I haven't found way to directly send html of original message

**Comment by ioanmo226** [comment]
Aha, I see. Sorry for confusion

**Comment by sosnovsky** [comment]
Yeah, probably my email text wasn't very clear :)

**Comment by ioanmo226** [comment]
@sosnovsky Upon checking, I found that the NSAttributedString initializer doesn't recognize the `xmlns` HTML (compatible with Microsoft Office email). As a result, the aforementioned HTML is treated like standard text and is thus rendered as such.

I can suggest 2 potential solutions for this issue:

1. Use an XML/HTML parser library, such as [Fuzi](https://github.com/cezheng/Fuzi) or [SwiftSoup](https://github.com/scinfu/SwiftSoup).
2. Opt for a webview instead of TextView.

Which option would you prefer?

**Comment by sosnovsky** [comment]
> Use an XML/HTML parser library, such as [Fuzi](https://github.com/cezheng/Fuzi) or [SwiftSoup](https://github.com/scinfu/SwiftSoup).

Looks like these libraries are not actively developed, so it'll be risky to be dependent on them for rendering messages.

> Opt for a webview instead of TextView.

We'll probably start using webview in the future, to be able to render html emails, not only plain text, but it'll be a bigger feature, here I thought it will be just a small fix.

Maybe we can just update doctype or replace `xmlns` to make it work with `NSAttributedString`?

**Comment by ioanmo226** [comment]
I see.
Let me try with this method.
> Maybe we can just update doctype or replace xmlns to make it work with NSAttributedString?
