### ISSUE TITLE
Use official SwiftLint plugin

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2278]
There is now official Xcode build tool plug-in from SwiftLint - https://github.com/realm/SwiftLint#plug-in-support, let's use it instead of current `SwiftLintPlugin`

**Comment by ioanmo226** [comment]
@sosnovsky Which installation method do you prefer?
Since we have removed CocoaPods and the .xcworkspace file, I think we should go with brew instead? We can then update the README to include this information.

![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/77344191/0ebf4e22-76e4-43d2-96c2-a928ff546022)

**Comment by sosnovsky** [comment]
`homebrew` sounds good, but maybe it's possible to use SwiftLint just with SPM package without need to additionally install it to OS?

**Comment by ioanmo226** [comment]
Already implemented with SPM. To do so we need to use SwiftLintPlugin (Xcode build tool).
Downside of this is, we can't access the executable directly and therefore we can't call/use it in CI mode.

**Comment by sosnovsky** [comment]
> Downside of this is, we can't access the executable directly and therefore we can't call/use it in CI mode.

We currently don't run `swiftlint` in CI, so it should be ok to have it only as editor plugin.
If we'll need it on CI in the future - we can just add `brew install swiftlint` to `semaphore.yml`
