### ISSUE TITLE
archive doesn't remove item from inbox until refreshed - sometimes

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#2366]
swiping item in inbox to archive it works well

clicking the archive button on opened message sometimes doesn't actually remove the item

only happened once, couldn't reproduce again

very likely afailed nil check somewhere. in which case, instead of doing nothing, whole inbox could be refreshed

**Comment by ioanmo226** [comment]
I wasn't able to reproduce the issue.
Right now, both swipe and details view use the same `handleOperation` function and it seems to work well.

We're already just updating or deleting the specific item that's affected, which I think is a good.
Refreshing the entire inbox might mess with the user's experience. (like he might loses scroll position, might take a bit time to reload full inbox items)

What do you think?

https://github.com/FlowCrypt/flowcrypt-ios/blob/e075e3c68627290212f7b036ed609b9a2f39bcee/FlowCrypt/Controllers/Inbox/InboxViewController+TableView.swift#L401

**Comment by sosnovsky** [comment]
I wasn't able to reproduce this issue too, maybe it was caused by network issues or other rare circumstances.

But I think we can still add handling of such cases here - https://github.com/FlowCrypt/flowcrypt-ios/blob/5fc8ba868fb755c02670b96463d64673780cbff3/FlowCrypt/Controllers/Inbox/InboxViewController%2BTableView.swift#L405, and perform inbox reload when `indexToUpdate` not found. It should be a quite rare case and won't affect user experience too much.

**Comment by ioanmo226** [comment]
Ok, Sounds good
