### ISSUE TITLE
mailcore2-ios http

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#302]
@tomholub please take a look 

From `pod instal` logs
```
'mailcore2-ios' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.
```

**Comment by tomholub** [comment]
Please see if there is something you could do Alex

**Comment by seisvelas** [comment]
This is fixed in master but they haven't done a release in a long time. They have an issue for it on their repo as well: https://github.com/MailCore/mailcore2/issues/1710, which offers a solution:

> @siberianisaev I got the same error, but it appears to be fixed in `master`, perhaps by https://github.com/MailCore/mailcore2/commit/b99e4eab5cc02bda9a723cd38b0a3a2393dd1e15. You can use it in your Podfile like this:
> ```
> pod 'mailcore2-ios', :git => 'https://github.com/MailCore/mailcore2.git', :commit => 'e6b4597d3b'
> ```

_Originally posted by @lehrblogger in https://github.com/MailCore/mailcore2/issues/1710#issuecomment-372904688_

So we should be able to switch to this in our Podfile:

    pod 'mailcore2-ios', :git => 'https://github.com/MailCore/mailcore2.git', :commit => '1434761'

to use commit https://github.com/MailCore/mailcore2/commit/1434761709b4d9dd5acc5b7185a3b32aa4845ba8 (currently the most recent one, or we could do the exact commit that fixed https)

I see we also have a Podfile.lock, so in addition to changing the Podfile, we'll have to regenerate and check in the updated lock.

Let me know if this jives with y'all's understanding of the situation!

**Comment by tomholub** [comment]
Sounds good to me, as a fix until they release a new version

**Comment by tomholub** [comment]
Thank you for looking into this!
