### ISSUE TITLE
hangs forever when importing key from a file

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#406]
This file has several keys all encrypted by the same pass phrase.

![image](https://user-images.githubusercontent.com/6306961/126630228-746e3758-9b2f-4dcc-a942-3f23f3d3950c.png)

It hangs forever after I click continue.

**Comment by tomholub** [comment]
This was observed both when adding a new account, and when setting up first account.

**Comment by ekievsky** [comment]
The problem is that on `SetupManuallyEnterPassPhraseViewController` we try to retrieve key details, which tries to get private keys from `EncryptedStorage`, returns `emptyKeys` error which is not handled. Seems that it's expected behaviour that if there is no keys in storage in should throw `emptyKeys` and we should allow user to proceed, because there couldn't be any keys if app just installed or if it's a new user on this device. Am I right?


One small thing, I was saving private key to disk using browser extension and it seems that I found a bug:
1. I set up the extension for my `evgenii@flowcrypt.com` email;
2. Open usual gmail website;
3. Open email `Your FlowCrypt Backup`;
4. There is a small delay until attached file is covered `TEST YOUT PASSPHRASE`;
5. So this delay allows me to download file without entering passphrase (you just need to click on download button really fast).

**Comment by tomholub** [comment]
> The problem is that on SetupManuallyEnterPassPhraseViewController we try to retrieve key details, which tries to get private keys from EncryptedStorage, returns emptyKeys error which is not handled. 

I don't think we should be throwing `emptyKeys` at all. The method should return an empty list.

> Seems that it's expected behaviour that if there is no keys in storage in should throw emptyKeys and we should allow user to proceed, because there couldn't be any keys if app just installed or if it's a new user on this device. Am I right?

We should not even be pulling keys from storage at that stage, I think. We know we are in setup flow, we know that keys were not set up yet, so it seems incorrect to try to pull them from the storage at all.

I may be missing some implementation detail specific to the iOS app, so don't take my words above to be 100% correct. However, you are right that it is expected that there are no keys in storage at this stage, until we import and store them.

**Comment by tomholub** [comment]
> One small thing, I was saving private key to disk using browser extension and it seems that I found a bug:
> 
>     1. I set up the extension for my `evgenii@flowcrypt.com` email;
> 
>     2. Open usual gmail website;
> 
>     3. Open email `Your FlowCrypt Backup`;
> 
>     4. There is a small delay until attached file is covered `TEST YOUT PASSPHRASE`;
> 
>     5. So this delay allows me to download file without entering passphrase (you just need to click on download button really fast).

Thank you for mentioning it (in case it was a problem). In this particular situation, it's not a problem - we're not trying to prevent the user from downloading the file. The file is theirs, and it's protected with the pass phrase either way.

**Comment by Kharchevskyi** [comment]
@ekievsky do you need help with this issue?

**Comment by ekievsky** [comment]
@Kharchevskyi sorry, missed your comment, I'm wrapping it up, thank you!
