### ISSUE TITLE
click on attachment on compose screen to view/download it

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#436]
same as https://github.com/FlowCrypt/flowcrypt-browser/issues/3896

eg, I attach an image. Now I'm not sure it's the right image (not obvious from name). I want to view it back to double check it.

**Comment by ioanmo226** [comment]
@tomholub 
This issue seems outdated. Please confirm
When I click on attachment in compose screen, it displays preview screen correctly.
If you want to show download button, we just need to `shouldShowDownloadButton` to `true`

![image](https://user-images.githubusercontent.com/77344191/174740529-689014df-f5e4-4952-96a1-5383ea4cfb80.png)

**Comment by tomholub** [comment]
Maybe it's ok as it is. If we can preview most files, maybe no need to download them back when composing. I think it's good.
