### ISSUE TITLE
"Check for email" failing

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#480]
https://github.com/FlowCrypt/flowcrypt-ios/runs/3488412705?check_suite_focus=true
Sometimes check for email action fails with `Error: Cannot read property 'match' of null`

**Comment by tomholub** [comment]
@IvanPizhenko https://github.com/FlowCrypt/flowcrypt-ios/invitations please have a look at the above github action - I've just forked it it from it's source, to be hosted on our org: https://github.com/FlowCrypt/comment-email-address-alerts/invitations

Please fix the issue, then point our GitHub action at our forked / fixed version instead of the seisvelas version.
