### ISSUE TITLE
DB migration

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#597]
Do we need to have DB migration or this is not important at this moment since we are not in production? For example we changed primary key and when I run `master` branch I get this error:
```
FlowCrypt/EncryptedStorage.swift:83: Fatal error: failed to initiate realm: Error Domain=io.realm Code=10 "Migration is required due to the following errors:
- Property 'KeyInfo.primaryFingerprint' has been added.
- Property 'KeyInfo.passphrase' has been added.
- Primary Key for class 'KeyInfo' has changed from 'private' to 'primaryFingerprint'." UserInfo={NSLocalizedDescription=Migration is required due to the following errors:
- Property 'KeyInfo.primaryFingerprint' has been added.
- Property 'KeyInfo.passphrase' has been added.
- Primary Key for class 'KeyInfo' has changed from 'private' to 'primaryFingerprint'., Error Code=10}
```
I understand that all I need is to reinstall the app but this could be not user friendly for beta testers or other people who using application (including developers).

**Comment by tomholub** [comment]
Thank you for asking this question. Indeed, for now we can skip migrations since we have no production users. Starting around November, we'll have to start including migrations. That's why I'm trying to make sure we do most of the needed schema changes before then.

I'll go ahead and close this issue - thanks again.
