### ISSUE TITLE
Can't fetch mails - SWIFT TASK CONTINUATION MISUSE

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#703]
App gives `SWIFT TASK CONTINUATION MISUSE` error when trying to open home screen:

<img width="479" alt="Screenshot 2021-10-18 at 22 51 49" src="https://user-images.githubusercontent.com/1062093/137797645-223b0d5e-3f3c-4f33-add9-5b30a691f0e5.png">

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-ios/issues/700#issuecomment-946113290_

**Comment by tomholub** [comment]
@ivan-ushakov I've reverted the last async/await change with https://github.com/FlowCrypt/flowcrypt-ios/commit/8abb46bfae9310bc32ab062bff106793856c4f70 . Please take a look.

**Comment by tomholub** [comment]
Are you able to finalize the threads in the next week or so? I was going to schedule it for later, since we are doing refactoring these days / knowing it would produce conflicts (that's why I put threads in later milestone). But if you could get it done in about a week then we could wait with the other stuff.

**Comment by ivan-ushakov** [comment]
For the history. Problem was a bit more complex. I used weak `gmailService` property inside continuation and haven't checked this this property is computational, so we create new `gmailService` instance each time. This leads to nil value in weak property so continuation never resume.
