### ISSUE TITLE
Reply button is missing on message screen

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#936]
![Simulator Screen Shot - iPhone 12 - 2021-11-05 at 22 18 06](https://user-images.githubusercontent.com/1062093/140573310-e87371fe-5c23-4d99-bea1-aba08c924935.png)

**Comment by tomholub** [comment]
This is asking for a UI test as well as follows:

1) open any conversation
2) tap the reply icon
3) verify that you are on reply screen, and verify the information that was prefilled:
   - to: 
   - quoted message content

will file another issue.

**Comment by tomholub** [comment]
No amount of unit tests would uncover these kinds of issues.

**Comment by tomholub** [comment]
Please add it next to each expanded conversation email, the way Gmail does it.

**Comment by tomholub** [comment]
The conversations PR was really half-baked. I've made an exception to merge it because of the never-ending merge conflicts, but in the future we cannot let that happen - the quality has to be enforced before a PR is merged.

Part of that will be human review and testing, and part will be automated ui tests.
